### ISSUE TITLE
/changeColor APIのリクエストBody

### ISSUE THREAD

**Issue by yutaroyoshikawa** [HALTermA/tee-pod#4]
# 概要
- `/changeColor` APIのリクエストボディのデータ設計について変更のお願い
- `functions/index.js` のchangeColor APIのソースコードのバグの報告

### なぜ
リクエストボディの形がすごく冗長になっているので、もっとスッキリさせるとアプリ側が実装しやすくなる

### お願い
現在、changeColorAPIのリクエストボディは
```
{
  "color": {
    "colors": {
      "normal": "normal"
    }
  }
}
```
のような感じになっているが、
```
{
  "color": "normal"
}
```
のようにリクエストを投げられるようにして欲しい

### なぜ
タイポがあってぱりぴモードの時のリクエストが通らない

### お願い
`index.js:L13` のpartyPeopleの定義が `paetyPeople` になっているので、 `pertyPeople` に修正して欲しい

**Comment by Micchili** [comment]
タイポはマジで申し訳ない、報告ありがとう☺
